#ifndef LCD_UI_LAYOUT_H
#define LCD_UI_LAYOUT_H

#define LCD_UI_WIDTH 320U
#define LCD_UI_HEIGHT 240U

#define LCD_UI_COLOR_BACKGROUND 0x0882U
#define LCD_UI_COLOR_PANEL 0x10C4U
#define LCD_UI_COLOR_PANEL_ALT 0x1905U
#define LCD_UI_COLOR_DIVIDER 0x29A7U
#define LCD_UI_COLOR_ACCENT 0x1E5AU
#define LCD_UI_COLOR_TEXT 0xEF9EU
#define LCD_UI_COLOR_MUTED 0x8CB4U
#define LCD_UI_COLOR_WEAK 0x530DU
#define LCD_UI_COLOR_PASS 0x468FU
#define LCD_UI_COLOR_FAIL 0xF2CCU
#define LCD_UI_COLOR_WARNING 0xF5C8U

#define LCD_UI_MARGIN_X 12U
#define LCD_UI_RIGHT_COLUMN_X 170U
#define LCD_UI_DIVIDER_X 159U
#define LCD_UI_HEADER_HEIGHT 36U
#define LCD_UI_HEADER_RULE_Y 36U
#define LCD_UI_HEADER_TITLE_Y 8U
#define LCD_UI_HEADER_PAGE_X 190U
#define LCD_UI_HEADER_PAGE_Y 9U
#define LCD_UI_HEADER_INDICATOR_X 222U
#define LCD_UI_HEADER_INDICATOR_Y 26U
#define LCD_UI_HEADER_INDICATOR_WIDTH 8U
#define LCD_UI_HEADER_INDICATOR_GAP 4U
#define LCD_UI_HEADER_ACCENT_START_Y 34U
#define LCD_UI_HEADER_ACCENT_END_X 92U

#define LCD_UI_PANEL_TOP_Y 40U
#define LCD_UI_PANEL_TOP_END_Y 110U
#define LCD_UI_PANEL_BOTTOM_Y 116U
#define LCD_UI_PANEL_BOTTOM_END_Y 195U
#define LCD_UI_FOOTER_RULE_Y 211U
#define LCD_UI_FOOTER_START_Y 216U
#define LCD_UI_FOOTER_TEXT_Y 220U

#define LCD_UI_MOTOR_MAIN_Y 40U
#define LCD_UI_MOTOR_MAIN_END_Y 168U
#define LCD_UI_MOTOR_SUMMARY_Y 172U
#define LCD_UI_MOTOR_SUMMARY_END_Y 205U

#define LCD_UI_SENSORS_MAIN_Y 40U
#define LCD_UI_SENSORS_MAIN_END_Y 112U
#define LCD_UI_SENSORS_SUMMARY_Y 118U
#define LCD_UI_SENSORS_SUMMARY_END_Y 195U

#define LCD_UI_SYSTEM_HEALTH_Y 40U
#define LCD_UI_SYSTEM_HEALTH_END_Y 75U
#define LCD_UI_SYSTEM_TASKS_Y 80U
#define LCD_UI_SYSTEM_TASKS_END_Y 133U
#define LCD_UI_SYSTEM_DIAGNOSTICS_Y 138U
#define LCD_UI_SYSTEM_DIAGNOSTICS_END_Y 205U

#define LCD_UI_LOGO_SIZE 32U
#define LCD_UI_LOGO_RIGHT_MARGIN 8U
#define LCD_UI_LOGO_Y 2U

#define LCD_UI_BATTERY_X 12U
#define LCD_UI_BATTERY_Y 88U
#define LCD_UI_BATTERY_WIDTH 288U
#define LCD_UI_BATTERY_HEIGHT 16U

#define LCD_UI_SYSTEM_TASK_ROW_1_Y 98U
#define LCD_UI_SYSTEM_TASK_ROW_2_Y 116U

#endif
