#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#define CHASSIS_FIRMWARE_VERSION "0.1.0"

#define ENABLE_BAREMETAL_MOTOR_DEMO 0

#define MOTOR_CONTROL_PERIOD_MS 10U
#define MOTOR_COMMAND_TIMEOUT_MS 200U
#define MOTOR_TELEMETRY_PERIOD_MS 100U
#define MOTOR_CONTROL_MAX_PENDING_TICKS 4U

/* Closed-loop limit: 80% of the 8500-count TIM8 PWM period. */
#define MOTOR_CONTROL_OUTPUT_LIMIT 6800
#define MOTOR_CONTROL_TARGET_LIMIT 100
#define MOTOR_LEFT_ENCODER_DIRECTION -1
#define MOTOR_RIGHT_ENCODER_DIRECTION 1

/* Initial hardware tuning values. They still require load testing. */
#define MOTOR_LEFT_PID_KP 200.0f
#define MOTOR_LEFT_PID_KI 300.0f
#define MOTOR_LEFT_PID_KD 0.0f
#define MOTOR_RIGHT_PID_KP 200.0f
#define MOTOR_RIGHT_PID_KI 300.0f
#define MOTOR_RIGHT_PID_KD 0.0f

#define MOTOR_DEMO_TARGET_COUNTS_PER_TICK 5
#define MOTOR_DEMO_STOP_TIME_MS 1000U
#define MOTOR_DEMO_RUN_TIME_MS 2000U

/* Explicit UART-confirmed bring-up test: 50% of TIM8 PWM period. */
#define MOTOR_OPEN_LOOP_TEST_DUTY 4250
#define MOTOR_OPEN_LOOP_TEST_DURATION_MS 1000U

#define MOTOR_SUPPLY_ADC_REFERENCE_MV 3300ULL
#define MOTOR_SUPPLY_DIVIDER_RATIO 11ULL
#define MOTOR_SUPPLY_ADC_MAX 4095ULL
#define MOTOR_SUPPLY_ADC_TIMEOUT_MS 2U

#endif
