#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include "adc.h"
#include "quadspi.h"
#include "spi.h"
#include "tim.h"

#define BOARD_MOTOR_TIMER htim8
#define BOARD_MOTOR_LEFT_POSITIVE_CHANNEL TIM_CHANNEL_1
#define BOARD_MOTOR_LEFT_NEGATIVE_CHANNEL TIM_CHANNEL_2
#define BOARD_MOTOR_RIGHT_POSITIVE_CHANNEL TIM_CHANNEL_4
#define BOARD_MOTOR_RIGHT_NEGATIVE_CHANNEL TIM_CHANNEL_3

#define BOARD_LEFT_ENCODER_TIMER htim2
#define BOARD_RIGHT_ENCODER_TIMER htim4
#define BOARD_LEFT_ENCODER_DIRECTION -1
#define BOARD_RIGHT_ENCODER_DIRECTION 1

#define BOARD_POWER_ADC hadc1
#define BOARD_POWER_ADC_REFERENCE_MV 3300ULL
#define BOARD_POWER_DIVIDER_RATIO 11ULL
#define BOARD_POWER_ADC_MAX 4095ULL
#define BOARD_POWER_ADC_TIMEOUT_MS 2U

#define BOARD_LCD_SPI hspi2
#define BOARD_LCD_BACKLIGHT_TIMER htim3
#define BOARD_LCD_BACKLIGHT_CHANNEL TIM_CHANNEL_1

#define BOARD_QSPI hqspi1

#endif
