#ifndef BOOTLOADER_BUILD_INFO_H
#define BOOTLOADER_BUILD_INFO_H

#define BOOTLOADER_VERSION_MAJOR 0U
#define BOOTLOADER_VERSION_MINOR 1U
#define BOOTLOADER_VERSION_PATCH 0U
#define BOOTLOADER_BUILD_NUMBER 21
#define BOOTLOADER_VERSION_STRING "0.1.0"

#define BOOTLOADER_STRINGIFY_VALUE(value) #value
#define BOOTLOADER_STRINGIFY(value) BOOTLOADER_STRINGIFY_VALUE(value)
#define BOOTLOADER_BUILD_STRING BOOTLOADER_STRINGIFY(BOOTLOADER_BUILD_NUMBER)

#endif
