#ifndef OTA_PROTOCOL_H
#define OTA_PROTOCOL_H

#define OTA_PROTOCOL_VERSION 1U

typedef enum
{
  OTA_SOURCE_NONE = 0,
  OTA_SOURCE_UART,
  OTA_SOURCE_CAN_FD
} OtaSource;

typedef enum
{
  OTA_MESSAGE_BEGIN = 1,
  OTA_MESSAGE_DATA,
  OTA_MESSAGE_END,
  OTA_MESSAGE_ABORT,
  OTA_MESSAGE_STATUS
} OtaMessageType;

typedef enum
{
  OTA_RESULT_OK = 0,
  OTA_RESULT_BUSY,
  OTA_RESULT_INVALID_STATE,
  OTA_RESULT_INVALID_HEADER,
  OTA_RESULT_INVALID_SEQUENCE,
  OTA_RESULT_INVALID_CRC,
  OTA_RESULT_NO_SPACE,
  OTA_RESULT_IO_ERROR,
  OTA_RESULT_TIMEOUT
} OtaResult;

#endif
