#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define MOTOR_CONTROL_MAX_MISSED_TICKS 4U
#define MOTOR_CONTROL_MAX_CONSECUTIVE_OVERRUNS 3U

#define MOTOR_DEMO_TARGET_COUNTS_PER_TICK 5
#define MOTOR_DEMO_STOP_TIME_MS 1000U
#define MOTOR_DEMO_RUN_TIME_MS 2000U

/* Voltage-only estimate for the current nominal 12 V battery setup. */
#define BATTERY_PERCENT_EMPTY_MV 9000U
#define BATTERY_PERCENT_FULL_MV 12600U

#endif
