#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define MOTOR_CONTROL_MAX_PENDING_TICKS 4U

#define MOTOR_DEMO_TARGET_COUNTS_PER_TICK 5
#define MOTOR_DEMO_STOP_TIME_MS 1000U
#define MOTOR_DEMO_RUN_TIME_MS 2000U

#endif
