#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define MOTOR_CONTROL_MAX_PENDING_TICKS 4U

#define MOTOR_DEMO_TARGET_COUNTS_PER_TICK 5
#define MOTOR_DEMO_STOP_TIME_MS 1000U
#define MOTOR_DEMO_RUN_TIME_MS 2000U

/* Explicit UART-confirmed bring-up test: 50% of TIM8 PWM period. */
#define MOTOR_OPEN_LOOP_TEST_DUTY 4250
#define MOTOR_OPEN_LOOP_TEST_DURATION_MS 1000U

#endif
