#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define CHASSIS_FIRMWARE_VERSION "1.0.1"
#define CHASSIS_FIRMWARE_BUILD 1

#define CHASSIS_BUILD_STRINGIFY_INNER(value) #value
#define CHASSIS_BUILD_STRINGIFY(value) CHASSIS_BUILD_STRINGIFY_INNER(value)
#define CHASSIS_FIRMWARE_BUILD_STRING \
  CHASSIS_BUILD_STRINGIFY(CHASSIS_FIRMWARE_BUILD)

#endif
