CONFIG_CAN=y
CONFIG_ICM45686=y
CONFIG_LCD=y
CONFIG_QSPI=y
CONFIG_OTA=y
CONFIG_TARGET_TEST=y
CONFIG_MOTOR_DEMO=n

CONFIG_CAN_RX_QUEUE_SIZE=8

CONFIG_CONTROL_TASK_STACK_SIZE=512
CONFIG_DIAGNOSTICS_TASK_STACK_SIZE=768
CONFIG_DISPLAY_TASK_STACK_SIZE=512

CONFIG_CONTROL_TASK_PRIORITY=54
CONFIG_SERVICE_TASK_PRIORITY=52
CONFIG_DIAGNOSTICS_TASK_PRIORITY=51
CONFIG_DISPLAY_TASK_PRIORITY=50

CONFIG_SERVICE_TASK_PERIOD_MS=1
CONFIG_CONTROL_TASK_PERIOD_MS=10
CONFIG_DIAGNOSTICS_TASK_PERIOD_MS=100
CONFIG_DISPLAY_TASK_PERIOD_MS=1

CONFIG_SERVICE_TASK_TIMEOUT_MS=200
CONFIG_CONTROL_TASK_TIMEOUT_MS=50
CONFIG_DIAGNOSTICS_TASK_TIMEOUT_MS=500
CONFIG_DISPLAY_TASK_TIMEOUT_MS=2000
