#ifndef STORAGE_LAYOUT_H
#define STORAGE_LAYOUT_H

#include "../../../shared/flash_layout.h"
#include "../../../shared/qspi_flash_identity.h"

#define QSPI_FLASH_SECTOR_SIZE 0x00001000UL
#define QSPI_FLASH_PAGE_SIZE 0x00000100UL

#define QSPI_PARAMETERS_START 0x00000000UL
#define QSPI_PARAMETERS_SIZE 0x00010000UL

#define QSPI_LOG_START 0x00010000UL
#define QSPI_LOG_SIZE 0x003F0000UL

#define QSPI_UPGRADE_METADATA_A_START OTA_QSPI_METADATA_A_START
#define QSPI_UPGRADE_METADATA_B_START OTA_QSPI_METADATA_B_START
#define QSPI_UPGRADE_SLOT_A_START OTA_QSPI_SLOT_A_START
#define QSPI_UPGRADE_SLOT_A_SIZE OTA_QSPI_SLOT_A_SIZE
#define QSPI_UPGRADE_SLOT_B_START OTA_QSPI_SLOT_B_START
#define QSPI_UPGRADE_SLOT_B_SIZE OTA_QSPI_SLOT_B_SIZE

#define QSPI_TEST_START 0x007FF000UL
#define QSPI_TEST_SIZE QSPI_FLASH_SECTOR_SIZE

#if (QSPI_UPGRADE_SLOT_B_START + QSPI_UPGRADE_SLOT_B_SIZE) > QSPI_TEST_START
#error "OTA slot B overlaps the target-test sector"
#endif

#if (QSPI_TEST_START + QSPI_TEST_SIZE) > QSPI_FLASH_CAPACITY_BYTES
#error "QSPI layout exceeds the flash capacity"
#endif

#endif
