#ifndef TARGET_TEST_CONFIG_H
#define TARGET_TEST_CONFIG_H

/* Explicit UART-confirmed bring-up test: about 76% of TIM8 PWM period. */
#define MOTOR_OPEN_LOOP_TEST_DUTY 6500
#define MOTOR_OPEN_LOOP_TEST_DURATION_MS 1000U

#define IWDG_TEST_BACKUP_REGISTER 2U
#define IWDG_TEST_MARKER 0x49574447UL

#endif
