#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include "adc.h"
#include "fdcan.h"
#include "iwdg.h"
#include "quadspi.h"
#include "rtc.h"
#include "spi.h"
#include "tim.h"
#include "usart.h"

#define BOARD_LED_BLUE_GPIO_PORT LED_B_GPIO_Port
#define BOARD_LED_BLUE_GPIO_PIN LED_B_Pin
#define BOARD_LED_GREEN_GPIO_PORT LED_G_GPIO_Port
#define BOARD_LED_GREEN_GPIO_PIN LED_G_Pin
#define BOARD_LED_RED_GPIO_PORT LED_R_GPIO_Port
#define BOARD_LED_RED_GPIO_PIN LED_R_Pin

#define BOARD_MOTOR_TIMER htim8
#define BOARD_MOTOR_LEFT_POSITIVE_CHANNEL TIM_CHANNEL_1
#define BOARD_MOTOR_LEFT_NEGATIVE_CHANNEL TIM_CHANNEL_2
#define BOARD_MOTOR_RIGHT_POSITIVE_CHANNEL TIM_CHANNEL_4
#define BOARD_MOTOR_RIGHT_NEGATIVE_CHANNEL TIM_CHANNEL_3

#define BOARD_LEFT_ENCODER_TIMER htim2
#define BOARD_RIGHT_ENCODER_TIMER htim4
#define BOARD_LEFT_ENCODER_DIRECTION -1
#define BOARD_RIGHT_ENCODER_DIRECTION 1

#define BOARD_POWER_ADC hadc1
#define BOARD_POWER_ADC_REFERENCE_MV 3300ULL
#define BOARD_POWER_DIVIDER_RATIO 11ULL
#define BOARD_POWER_ADC_MAX 4095ULL
#define BOARD_POWER_ADC_TIMEOUT_MS 2U
#define BOARD_LCD_SPI hspi2
#define BOARD_LCD_CS_GPIO_PORT LCD_CS_GPIO_Port
#define BOARD_LCD_CS_GPIO_PIN LCD_CS_Pin
#define BOARD_LCD_DC_GPIO_PORT LCD_DC_GPIO_Port
#define BOARD_LCD_DC_GPIO_PIN LCD_DC_Pin
#define BOARD_LCD_RESET_GPIO_PORT LCD_RST_GPIO_Port
#define BOARD_LCD_RESET_GPIO_PIN LCD_RST_Pin
#define BOARD_LCD_BACKLIGHT_TIMER htim3
#define BOARD_LCD_BACKLIGHT_CHANNEL TIM_CHANNEL_1

#define BOARD_IMU_SPI hspi3
#define BOARD_IMU_CS_GPIO_PORT IMU_CS_GPIO_Port
#define BOARD_IMU_CS_GPIO_PIN IMU_CS_Pin
#define BOARD_IMU_INTERRUPT_GPIO_PIN IMU_INT1_Pin

#define BOARD_EMERGENCY_STOP_GPIO_PORT E_STOP_GPIO_Port
#define BOARD_EMERGENCY_STOP_GPIO_PIN E_STOP_Pin

#define BOARD_BUTTON_1_GPIO_PORT BUTTON_1_GPIO_Port
#define BOARD_BUTTON_1_GPIO_PIN BUTTON_1_Pin
#define BOARD_BUTTON_2_GPIO_PORT BUTTON_2_GPIO_Port
#define BOARD_BUTTON_2_GPIO_PIN BUTTON_2_Pin
#define BOARD_DISPLAY_KEY_GPIO_PORT KEY_GPIO_Port
#define BOARD_DISPLAY_KEY_GPIO_PIN KEY_Pin

#define BOARD_SR501_GPIO_PORT SR501_OUT_GPIO_Port
#define BOARD_SR501_GPIO_PIN SR501_OUT_Pin

#define BOARD_QSPI hqspi1
#define BOARD_FDCAN hfdcan2
#define BOARD_RTC hrtc
#define BOARD_UART huart1
#define BOARD_WATCHDOG hiwdg

#endif
