set(APP_ROOT "${CMAKE_SOURCE_DIR}/firmware/application/stm32g474")

set(APP_SOURCES
  Application/User/Core/syscalls.c
  Application/User/Core/sysmem.c
  Application/User/Startup/startup_stm32g474vetx.s
  Core/Src/adc.c
  Core/Src/app_freertos.c
  Core/Src/dma.c
  Core/Src/fdcan.c
  Core/Src/gpio.c
  Core/Src/iwdg.c
  Core/Src/main.c
  Core/Src/quadspi.c
  Core/Src/rtc.c
  Core/Src/spi.c
  Core/Src/stm32g4xx_hal_msp.c
  Core/Src/stm32g4xx_hal_timebase_tim.c
  Core/Src/stm32g4xx_it.c
  Core/Src/system_stm32g4xx.c
  Core/Src/tim.c
  Core/Src/usart.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fdcan.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_iwdg.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_qspi.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rtc.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rtc_ex.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi_ex.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c
  Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c
  Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c
  Middlewares/Third_Party/FreeRTOS/Source/croutine.c
  Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
  Middlewares/Third_Party/FreeRTOS/Source/list.c
  Middlewares/Third_Party/FreeRTOS/Source/queue.c
  Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
  Middlewares/Third_Party/FreeRTOS/Source/tasks.c
  Middlewares/Third_Party/FreeRTOS/Source/timers.c
  Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c
  Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
  app/chassis_app.c
  bsp/button/bsp_button.c
  bsp/encoder/bsp_encoder.c
  bsp/fdcan/fdcan_bsp.c
  bsp/lcd/bsp_lcd.c
  bsp/imu/bsp_icm45686.c
  bsp/motor/bsp_motor.c
  bsp/power_monitor/bsp_power_sample.c
  bsp/qspi/bsp_qspi_flash.c
  bsp/reset/bsp_reset.c
  bsp/sr501/bsp_sr501.c
  bsp/uart/uart_bsp.c
  communication/can_transport/can_transport.c
  communication/ota_transport/ota_can_transport.c
  communication/ota_transport/ota_confirmation.c
  communication/ota_transport/ota_metadata.c
  communication/ota_transport/ota_session.c
  communication/ota_transport/ota_uart_transport.c
  components/crc/crc32.c
  components/icm45686/icm45686.c
  components/imu_fusion/imu_fusion.c
  components/pid/speed_pid.c
  infrastructure/console/console.c
  infrastructure/console/diagnostic_report.c
  infrastructure/parameter_storage/parameter_record.c
  infrastructure/parameter_storage/parameter_storage.c
  infrastructure/status_display/status_display.c
  infrastructure/telemetry/telemetry.c
  infrastructure/uart_protocol/uart_protocol.c
  modules/chassis/command_manager.c
  modules/chassis/differential_drive.c
  modules/chassis/odometry.c
  modules/chassis/wheel_controller.c
  modules/diagnostics/board_health.c
  modules/diagnostics/system_status.c
  modules/parameters/parameter_manager.c
  modules/safety/fault_manager.c
  modules/safety/safety_manager.c
  rtos/rtos_app.c
  tests/target/iwdg_target_test.c
  tests/target/motor_target_test.c
  tests/target/qspi_target_test.c
  tests/unit/test_command_manager.c
  tests/unit/test_icm45686.c
  tests/unit/test_imu_fusion.c
  tests/unit/test_ota_metadata.c
  tests/unit/test_parameter_record.c
  tests/unit/test_uart_protocol.c)
list(TRANSFORM APP_SOURCES PREPEND "${APP_ROOT}/")

add_executable(application ${APP_SOURCES})
target_include_directories(application PRIVATE
  "${APP_ROOT}"
  "${APP_ROOT}/Core/Inc"
  "${APP_ROOT}/Drivers/STM32G4xx_HAL_Driver/Inc"
  "${APP_ROOT}/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy"
  "${APP_ROOT}/Drivers/CMSIS/Device/ST/STM32G4xx/Include"
  "${APP_ROOT}/Drivers/CMSIS/Include"
  "${APP_ROOT}/Middlewares/Third_Party/FreeRTOS/Source/include"
  "${APP_ROOT}/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2"
  "${APP_ROOT}/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F")
target_compile_definitions(application PRIVATE
  USER_VECT_TAB_ADDRESS VECT_TAB_OFFSET=0x00008000U
  $<$<CONFIG:Debug>:APP_DEBUG_IWDG_FREEZE>)
stm32g474_target(application
  "${APP_ROOT}/STM32G474VETX_FLASH.ld" "application.map")
