#!/usr/bin/env python3

import argparse
import select
import socket
import struct
import sys
import time

from ota_transfer import (
    CAN_DATA_SIZE,
    CAN_FRAME_SIZE,
    CAN_REQUEST_ID,
    MessageType,
    OtaError,
    decode_can_response,
    encode_can_request,
    load_package,
    new_session_id,
    transfer_package,
)


CAN_RAW_FD_FRAMES = 5
CANFD_BRS = 0x01
CANFD_FRAME_FORMAT = "=IBB2x64s"
CANFD_FRAME_LENGTH = struct.calcsize(CANFD_FRAME_FORMAT)


def pack_canfd(can_id, payload):
    if len(payload) != CAN_FRAME_SIZE:
        raise OtaError("OTA CAN FD frame must contain 64 data bytes")
    return struct.pack(CANFD_FRAME_FORMAT, can_id, len(payload), CANFD_BRS, payload)


def receive_response(can_socket, session_id, timeout):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        readable, _, _ = select.select(
            [can_socket], [], [], max(0.0, deadline - time.monotonic())
        )
        if not readable:
            break
        frame = can_socket.recv(CANFD_FRAME_LENGTH)
        if len(frame) != CANFD_FRAME_LENGTH:
            continue
        can_id, length, _flags, payload = struct.unpack(CANFD_FRAME_FORMAT, frame)
        response = decode_can_response(can_id & 0x7FF, payload[:length])
        if response is not None and response[0] == session_id:
            return response
    return None


def main():
    parser = argparse.ArgumentParser(description="Send an OTA package over CAN FD.")
    parser.add_argument("interface", help="SocketCAN interface, for example can0")
    parser.add_argument("package", help=".ota package generated by package_firmware.py")
    parser.add_argument("--timeout", type=float, default=6.0)
    parser.add_argument("--retries", type=int, default=3)
    args = parser.parse_args()

    if not hasattr(socket, "AF_CAN"):
        parser.error("SocketCAN is only available on supported Linux systems")
    package = load_package(args.package)
    session_id = new_session_id()
    can_socket = socket.socket(socket.AF_CAN, socket.SOCK_RAW, socket.CAN_RAW)
    try:
        can_socket.setsockopt(socket.SOL_CAN_RAW, CAN_RAW_FD_FRAMES, 1)
        can_socket.bind((args.interface,))

        def exchange(message_type, current_session, argument=0, data=b""):
            payload = encode_can_request(
                message_type, current_session, argument, data
            )
            frame = pack_canfd(CAN_REQUEST_ID, payload)
            for _attempt in range(args.retries + 1):
                can_socket.send(frame)
                response = receive_response(
                    can_socket, current_session, args.timeout
                )
                if response is not None:
                    return response
            raise OtaError(f"no response to {MessageType(message_type).name}")

        response = transfer_package(exchange, package, CAN_DATA_SIZE, session_id)
        print(
            f"OTA staged over CAN FD: session={session_id} "
            f"next_offset={response[3]}; device reset expected"
        )
    except (OSError, OtaError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    finally:
        can_socket.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
