#!/usr/bin/env python3

import argparse
import sys
import time

from ota_transfer import (
    MessageType,
    OtaError,
    UART_DATA_SIZE,
    UART_HEADER_SIZE,
    UART_MAGIC,
    decode_uart_response,
    encode_uart_request,
    load_package,
    new_session_id,
    transfer_package,
)


def is_ota_ready_response(line):
    tokens = line.strip().split()
    fields = {}

    if not tokens or tokens[0] != b"[RSP]":
        return False
    for token in tokens[1:]:
        if b"=" not in token:
            continue
        key, value = token.split(b"=", 1)
        if key in fields:
            return False
        fields[key] = value
    return (fields.get(b"result") == b"OK" and
            fields.get(b"command") == b"ota_uart")


def read_ready(serial_port, timeout):
    deadline = time.monotonic() + timeout
    received = bytearray()
    while time.monotonic() < deadline:
        received.extend(serial_port.read(serial_port.in_waiting or 1))
        while b"\n" in received:
            newline = received.index(b"\n")
            line = bytes(received[:newline])
            del received[:newline + 1]
            if is_ota_ready_response(line):
                return
    raise OtaError("device did not enter UART OTA mode")


def read_response(serial_port, session_id, timeout):
    deadline = time.monotonic() + timeout
    buffer = bytearray()
    while time.monotonic() < deadline:
        buffer.extend(serial_port.read(serial_port.in_waiting or 1))
        magic_offset = buffer.find(UART_MAGIC)
        if magic_offset < 0:
            if len(buffer) > 1:
                del buffer[:-1]
            continue
        if magic_offset:
            del buffer[:magic_offset]
        if len(buffer) < UART_HEADER_SIZE:
            continue
        frame_length = UART_HEADER_SIZE + buffer[5] + 4
        if len(buffer) < frame_length:
            continue
        frame = bytes(buffer[:frame_length])
        del buffer[:frame_length]
        response = decode_uart_response(frame)
        if response is not None and response[0] == session_id:
            return response
    return None


def main():
    parser = argparse.ArgumentParser(description="Send an OTA package over USART1.")
    parser.add_argument("port", help="serial port, for example COM7 or /dev/ttyUSB0")
    parser.add_argument("package", help=".ota package generated by package_firmware.py")
    parser.add_argument("--baud", type=int, default=115200)
    parser.add_argument("--timeout", type=float, default=6.0)
    parser.add_argument("--retries", type=int, default=3)
    parser.add_argument(
        "--post-reset-log-seconds",
        type=float,
        default=0.0,
        help="print serial output for this many seconds after STAGED",
    )
    args = parser.parse_args()

    try:
        import serial
    except ImportError:
        parser.error("pyserial is required: python -m pip install pyserial")

    package = load_package(args.package)
    session_id = new_session_id()
    try:
        with serial.Serial(args.port, args.baud, timeout=0.05) as serial_port:
            serial_port.reset_input_buffer()
            serial_port.write(b"telemetry off\r\n")
            time.sleep(0.1)
            serial_port.reset_input_buffer()
            serial_port.write(b"ota uart confirm\r\n")
            read_ready(serial_port, args.timeout)
            serial_port.reset_input_buffer()

            def exchange(message_type, current_session, argument=0, data=b""):
                frame = encode_uart_request(
                    message_type, current_session, argument, data
                )
                for _attempt in range(args.retries + 1):
                    serial_port.write(frame)
                    response = read_response(
                        serial_port, current_session, args.timeout
                    )
                    if response is not None:
                        return response
                raise OtaError(f"no response to {MessageType(message_type).name}")

            response = transfer_package(
                exchange, package, UART_DATA_SIZE, session_id
            )
            print(
                f"OTA staged over UART: session={session_id} "
                f"next_offset={response[3]}; device reset expected",
                flush=True,
            )
            if args.post_reset_log_seconds > 0:
                deadline = time.monotonic() + args.post_reset_log_seconds
                while time.monotonic() < deadline:
                    data = serial_port.read(serial_port.in_waiting or 1)
                    if data:
                        sys.stdout.buffer.write(data)
                        sys.stdout.buffer.flush()
    except (OSError, OtaError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
